export const books = [
    {
        title:,
        author:,
        image: "https://images-eu.ssl-images-amazon.com/images/I/81evNO+JD-L._AC._SR360,460.jpg",
    },
    {
        title:,
        author:,
        image:,
    },
    {
        title:,
        author:,
        image:,
    },
    {
        title:,
        author:,
        image:,
    },
    {
        title:,
        author:,
        image:,
    },
    {
        title:,
        author:,
        image:,
    },
]